apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-vpn-seed-server=allowed'
      to talk to's Kubernetes API Server.
  name: allow-to-vpn-seed-server
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      gardener.cloud/role: controlplane
      app: vpn-seed-server
  ingress:
  - from:
    - podSelector:
        matchLabels:
          gardener.cloud/role: controlplane
          app: kubernetes
          role: apiserver
  - from:
    - namespaceSelector: {} # we don't want to modify existing labels on the istio namespace
      podSelector:
        matchLabels:
          app: istio-ingressgateway
  egress:
  - to:
    - podSelector:
        matchLabels:
          gardener.cloud/role: controlplane
          app: kubernetes
          role: apiserver
  policyTypes:
  - Ingress
  - Egress

