apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-seed-server
  namespace: {{ .Release.Namespace }}
  labels:
    gardener.cloud/role: controlplane
    app: vpn-seed-server
    networking.gardener.cloud/from-shoot-apiserver: allowed
spec:
  minReadySeconds: 30
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  selector:
    matchLabels:
      app: vpn-seed-server
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        checksum/secret-vpn-seed-server-dh: {{ include (print $.Template.BasePath "/secret-dh.yaml") . | sha256sum }}
        checksum/secret-vpn-seed-server-tlsauth: {{ include (print $.Template.BasePath "/secret-tlsauth.yaml") . | sha256sum }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        gardener.cloud/role: controlplane
        garden.sapcloud.io/role: controlplane
        app: vpn-seed-server
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-private-networks: allowed
        networking.gardener.cloud/to-shoot-networks: allowed
        networking.gardener.cloud/from-prometheus: allowed
    spec:
      priorityClassName: system-cluster-critical
      dnsPolicy: Default # make sure to not use the coredns for DNS resolution.
      containers:
      - name: vpn-seed-server
        image: {{ index .Values.images "vpn-seed-server" }}
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE_NETWORK
          value: {{ .Values.serviceNetwork }}
        - name: POD_NETWORK
          value: {{ .Values.podNetwork }}
        {{- if .Values.nodeNetwork }}
        - name: NODE_NETWORK
          value: {{ .Values.nodeNetwork }}
        {{- end }}
        ports:
        - name: tcp-tunnel
          containerPort: 1194
          protocol: TCP
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
          {{- if .Values.vpaEnabled }}
            cpu: 400m
            memory: 400Mi
          {{- else }}
            cpu: "1"
            memory: 1Gi
          {{- end }}
        volumeMounts:
        - mountPath: /srv/secrets/vpn-server
          name: vpn-seed-server
        - mountPath: /srv/secrets/tlsauth
          name: vpn-seed-server-tlsauth
        - mountPath: /srv/secrets/dh
          name: vpn-seed-server-dh
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vpn-seed-server
        secret:
          secretName: vpn-seed-server
      - name: vpn-seed-server-tlsauth
        secret:
          secretName: vpn-seed-server-tlsauth
      - name: vpn-seed-server-dh
        secret:
          secretName: vpn-seed-server-dh

