---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: vpn-seed-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ .Values.internalDNSNameApiserver }}
    port:
      name: tls-tunnel
      number: 8132
      protocol: HTTP
