---
apiVersion: v1
kind: Secret
metadata:
  name: vpn-seed-server
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.vpnSeedServerSecretData.ca }}
  tls.crt: {{ .Values.vpnSeedServerSecretData.tlsCrt }}
  tls.key: {{ .Values.vpnSeedServerSecretData.tlsKey }}
