apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.istio.io/exportTo: '*'
  name: vpn-seed-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: vpn-seed-server
    port: 1194
    targetPort: 1194
  selector:
    app: vpn-seed-server
