apiVersion: v1
kind: Secret
metadata:
  name: wireguard-secret
  namespace: wireguard
stringData:
  wg0.conf: |+
    [Interface]
    Address = {{ .Values.wireguard.address }}
    PrivateKey = {{ .Values.wireguard.privateKey }}
    ListenPort = {{ .Values.wireguard.internalPort }}
    
    [Peer]
    PublicKey = {{ .Values.wireguard.peerPublicKey }}
    PresharedKey = {{ .Values.wireguard.peerPresharedKey }}
    AllowedIPs = {{ .Values.wireguard.peerAllowedIPs }}
